# drone secrets:
# repository = registry.domain.tld/namespace/image-name
# ssh_username
# ssh_host_dev
# ssh_host_prd
# ssh_key

kind: pipeline
name: "publish"
type: docker

trigger:
  event:
    - push
    - tag
  ref:
    - refs/heads/flyingfishflash
    - refs/tags/*

steps:
  - name: fetch git tags
    image: alpine/git
    commands:
      - git fetch --tags

  - name: publish development
    image: plugins/docker
    depends_on:
      - "fetch git tags"
    settings:
      auto_tag: false
      # custom_dns:
      #   from_secret: custom_dns
      registry:
        from_secret: registry_hostname
      repo:
        from_secret: repository
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      tags: development
    when:
      ref:
        - refs/heads/flyingfishflash

  - name: create tag list
    image: alpine/git
    commands:
      - echo -n "latest,${DRONE_TAG}" > .tags
    when:
      ref:
        - refs/tags/*-flyingfishflash

  - name: publish release
    image: plugins/docker
    depends_on:
      - "create tag list"
    settings:
      auto_tag: false
      # custom_dns:
      #   from_secret: custom_dns
      registry:
        from_secret: registry_hostname
      repo:
        from_secret: repository
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
    when:
      ref:
        - refs/tags/*-flyingfishflash
